"""add schools users tables and tenant columns

Revision ID: b82ead1cd54a
Revises: c1a108d1a444
Create Date: 2026-03-13 21:53:01.194881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82ead1cd54a'
down_revision: Union[str, Sequence[str], None] = 'c1a108d1a444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), server_default='', nullable=False),
    sa.Column('role', sa.String(length=20), server_default='teacher', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('scoring_sessions') as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_sessions_school', 'schools', ['school_id'], ['id'])
        batch_op.create_foreign_key('fk_sessions_user', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_sessions') as batch_op:
        batch_op.drop_constraint('fk_sessions_user', type_='foreignkey')
        batch_op.drop_constraint('fk_sessions_school', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('school_id')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
