"""initial scoring_sessions table

Revision ID: c1a108d1a444
Revises: 
Create Date: 2026-03-13 14:00:23.189091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a108d1a444'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_sessions',
    sa.Column('session_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default='', nullable=False),
    sa.Column('rubric_title', sa.Text(), server_default='', nullable=False),
    sa.Column('pdf_filename', sa.Text(), server_default='', nullable=False),
    sa.Column('pages_per_student', sa.Integer(), server_default='1', nullable=False),
    sa.Column('grading_mode', sa.Text(), server_default='legacy', nullable=False),
    sa.Column('students', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('ocr_results', sa.JSON(), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_sessions')
    # ### end Alembic commands ###
